# -*- coding: utf-8 -*-
"""crowd_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H7PJTvPD0WMS6JaRWip1y2w734a8zpzQ
"""

import random

from config import (
    HOURLY_FACTORS,
    RANDOM_MIN,
    RANDOM_MAX,
    LOW_THRESHOLD,
    MEDIUM_THRESHOLD,
    HIGH_THRESHOLD,
    RESOURCE_MAPPING
)

# ==========================================
# HOUR FACTOR
# ==========================================

def get_hour_factor(hour):

    if 6 <= hour < 10:
        return HOURLY_FACTORS[
            "early_morning"
        ]

    elif 10 <= hour < 15:
        return HOURLY_FACTORS[
            "peak_hours"
        ]

    elif 15 <= hour < 18:
        return HOURLY_FACTORS[
            "afternoon"
        ]

    elif 18 <= hour < 23:
        return HOURLY_FACTORS[
            "evening"
        ]

    return HOURLY_FACTORS[
        "night"
    ]


# ==========================================
# VISITOR COUNT
# ==========================================

def generate_visitor_count(
    max_capacity,
    popularity_weight,
    weather_factor,
    event_multiplier,
    hour_factor
):

    base_visitors = (

        max_capacity
        * popularity_weight
        * random.uniform(
            0.10,
            0.25
        )
    )

    visitors = (

        base_visitors
        * weather_factor
        * event_multiplier
        * hour_factor
        * random.uniform(
            RANDOM_MIN,
            RANDOM_MAX
        )
    )

    visitors = int(
        min(
            visitors,
            max_capacity
        )
    )

    return visitors


# ==========================================
# CROWD DENSITY
# ==========================================

def calculate_crowd_density(
    visitor_count,
    max_capacity
):

    if max_capacity == 0:
        return 0

    return round(
        visitor_count / max_capacity,
        2
    )


# ==========================================
# CROWD LEVEL
# ==========================================

def get_crowd_level(
    crowd_density
):

    if crowd_density < LOW_THRESHOLD:
        return "Low"

    elif crowd_density < MEDIUM_THRESHOLD:
        return "Medium"

    elif crowd_density < HIGH_THRESHOLD:
        return "High"

    return "Critical"


# ==========================================
# RESOURCE USAGE
# ==========================================

def get_resource_usage(
    crowd_level
):

    return RESOURCE_MAPPING[
        crowd_level
    ]


# ==========================================
# NOISE LEVEL
# ==========================================

def calculate_noise_level(
    crowd_density
):

    noise = (
        40
        + (crowd_density * 50)
    )

    return round(
        noise,
        1
    )


# ==========================================
# SATISFACTION SCORE
# ==========================================

def calculate_satisfaction_score(
    crowd_density
):

    score = (
        100
        - (crowd_density * 50)
    )

    score += random.uniform(
        -5,
        5
    )

    score = max(
        min(score, 100),
        0
    )

    return round(
        score,
        1
    )


# ==========================================
# PEAK FLAG
# ==========================================

def get_peak_flag(
    crowd_density
):

    return int(
        crowd_density >= HIGH_THRESHOLD
    )