# -*- coding: utf-8 -*-
"""historical_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4FC0sFlnxMPy0IuO4ZMhU7BYIayeKkg
"""

"""
historical_rules.py
Spirit of Ankh - Historical Tourism Dataset Generator

Centralized business rules for:
- Tourism seasons
- School vacations
- Holidays
- Events
- Weekend effects
- Crowd status
- Context multipliers
"""

from datetime import datetime

# ==========================================================
# TOURISM SEASONS BY CITY
# ==========================================================

TOURISM_SEASONS = {

    "Cairo": {
        "Peak": [11, 12, 1, 2],
        "High": [3, 4, 10],
        "Normal": [5, 9],
        "Low": [6, 7, 8]
    },

    "Giza": {
        "Peak": [11, 12, 1, 2],
        "High": [3, 4, 10],
        "Normal": [5, 9],
        "Low": [6, 7, 8]
    },

    "Luxor": {
        "Peak": [11, 12, 1, 2],
        "High": [3, 4, 10],
        "Normal": [5, 9],
        "Low": [6, 7, 8]
    },

    "Aswan": {
        "Peak": [11, 12, 1, 2],
        "High": [3, 4, 10],
        "Normal": [5, 9],
        "Low": [6, 7, 8]
    },

    "Alexandria": {
        "Peak": [6, 7, 8],
        "High": [5, 9],
        "Normal": [4, 10],
        "Low": [11, 12, 1, 2, 3]
    },

    "Hurghada": {
        "Peak": [6, 7, 8, 12, 1],
        "High": [4, 5, 9, 10],
        "Normal": [2, 3, 11],
        "Low": []
    },

    "Sharm El Sheikh": {
        "Peak": [6, 7, 8, 12, 1],
        "High": [4, 5, 9, 10],
        "Normal": [2, 3, 11],
        "Low": []
    },

    "Dahab": {
        "Peak": [6, 7, 8],
        "High": [4, 5, 9, 10],
        "Normal": [11, 12, 1, 2, 3],
        "Low": []
    },

    "Fayoum": {
        "Peak": [10, 11, 12, 1, 2, 3],
        "High": [4, 5],
        "Normal": [9],
        "Low": [6, 7, 8]
    }
}


# ==========================================================
# SEASON MULTIPLIERS
# ==========================================================

SEASON_MULTIPLIERS = {
    "Peak": 1.50,
    "High": 1.25,
    "Normal": 1.00,
    "Low": 0.75
}


# ==========================================================
# CITY TOURISM WEIGHT
# Used later in visitor generation
# ==========================================================




# ==========================================================
# SCHOOL VACATIONS
# ==========================================================

SUMMER_VACATION_MONTHS = [6, 7, 8]

MIDYEAR_VACATION_MONTHS = [1]

VACATION_MULTIPLIERS = {
    "summer": 1.25,
    "midyear": 1.15,
    "none": 1.00
}


# ==========================================================
# WEEKEND
# Egypt: Friday + Saturday
# ==========================================================

WEEKEND_MULTIPLIER = 1.15


# ==========================================================
# HOLIDAY MULTIPLIERS
# ==========================================================

HOLIDAY_MULTIPLIERS = {

    "National Holiday": 1.15,

    "Religious Holiday": 1.30,

    "Eid Al Fitr": 1.50,

    "Eid Al Adha": 1.60,

    "Christmas": 1.10,

    "New Year": 1.10,

    "Event": 1.20,

    "Regular": 1.00
}




# ==========================================================
# CROWD STATUS
# ==========================================================

def get_crowd_status(occupancy_rate: float) -> str:

    if occupancy_rate >= 0.90:
        return "Overcrowded"

    elif occupancy_rate >= 0.70:
        return "Busy"

    elif occupancy_rate >= 0.40:
        return "Moderate"

    return "Low"


# ==========================================================
# CITY WEIGHT
# ==========================================================




# ==========================================================
# TOURISM SEASON
# ==========================================================

def get_tourism_season(city: str, month: int) -> str:

    city_rules = TOURISM_SEASONS.get(city)

    if not city_rules:
        return "Normal"

    for season_name, months in city_rules.items():

        if month in months:
            return season_name

    return "Normal"


# ==========================================================
# SEASON MULTIPLIER
# ==========================================================

def get_season_multiplier(city: str, month: int) -> float:

    season = get_tourism_season(city, month)

    return SEASON_MULTIPLIERS.get(season, 1.0)


# ==========================================================
# SCHOOL VACATION
# ==========================================================

def get_school_vacation(month: int):

    if month in SUMMER_VACATION_MONTHS:
        return True, "summer"

    if month in MIDYEAR_VACATION_MONTHS:
        return True, "midyear"

    return False, "none"


def get_vacation_multiplier(month: int):

    _, vacation_type = get_school_vacation(month)

    return VACATION_MULTIPLIERS[vacation_type]


# ==========================================================
# WEEKEND
# ==========================================================

def is_weekend(timestamp: datetime) -> bool:

    return timestamp.weekday() in [4, 5]


def get_weekend_multiplier(timestamp: datetime):

    if is_weekend(timestamp):
        return WEEKEND_MULTIPLIER

    return 1.0


# ==========================================================
# HOLIDAY MULTIPLIER
# ==========================================================

def get_holiday_multiplier(
    is_holiday: bool,
    holiday_type: str = "Regular"
):

    if not is_holiday:
        return 1.0

    return HOLIDAY_MULTIPLIERS.get(
        holiday_type,
        1.15
    )


# ==========================================================
# EVENT MULTIPLIER
# ==========================================================



# ==========================================================
# MASTER CONTEXT ENGINE
# ==========================================================

def get_context_score(
    city: str,
    timestamp: datetime,
    is_holiday: bool = False,
    holiday_type: str = "Regular",
    event_multiplier: float = 1.0
):

    month = timestamp.month

    season_multiplier = get_season_multiplier(
        city,
        month
    )

    vacation_multiplier = get_vacation_multiplier(
        month
    )

    weekend_multiplier = get_weekend_multiplier(
        timestamp
    )

    holiday_multiplier = get_holiday_multiplier(
        is_holiday,
        holiday_type
    )

    event_multiplier = 1.0

    total_multiplier = (
    season_multiplier
    * vacation_multiplier
    * weekend_multiplier
    * holiday_multiplier
    * event_multiplier
)

    # Prevent unrealistic explosion
    total_multiplier = min(
        total_multiplier,
        2.50
    )

    return {

        "tourism_season": get_tourism_season(
            city,
            month
        ),

        "season_multiplier": season_multiplier,

        "vacation_multiplier": vacation_multiplier,

        "weekend_multiplier": weekend_multiplier,

        "holiday_multiplier": holiday_multiplier,

        "event_multiplier": event_multiplier,



        "total_multiplier": round(
            total_multiplier,
            3
        )
    }

"""
historical_weather.py
Spirit of Ankh - Historical Weather Engine

Generates realistic simulated weather
for Egyptian tourism locations.

Output:
--------
temperature_c
weather_condition
is_real_weather=False
"""

import random

# ==========================================================
# CITY CLIMATE PROFILES
# Seasonal Average Temperatures (°C)
# ==========================================================

CITY_CLIMATE = {

    "Cairo": {
        "winter": 18,
        "spring": 27,
        "summer": 36,
        "autumn": 28
    },

    "Giza": {
        "winter": 18,
        "spring": 28,
        "summer": 37,
        "autumn": 29
    },

    "Alexandria": {
        "winter": 16,
        "spring": 23,
        "summer": 30,
        "autumn": 24
    },

    "Luxor": {
        "winter": 22,
        "spring": 34,
        "summer": 43,
        "autumn": 35
    },

    "Aswan": {
        "winter": 24,
        "spring": 36,
        "summer": 45,
        "autumn": 37
    },

    "Sharm El Sheikh": {
        "winter": 22,
        "spring": 30,
        "summer": 38,
        "autumn": 31
    },

    "Hurghada": {
        "winter": 21,
        "spring": 31,
        "summer": 37,
        "autumn": 30
    },

    "Dahab": {
        "winter": 20,
        "spring": 29,
        "summer": 35,
        "autumn": 29
    },

    "Fayoum": {
        "winter": 17,
        "spring": 28,
        "summer": 39,
        "autumn": 29
    }
}


# ==========================================================
# SEASON DETECTION
# ==========================================================

def get_season(month: int):

    if month in [12, 1, 2]:
        return "winter"

    elif month in [3, 4, 5]:
        return "spring"

    elif month in [6, 7, 8]:
        return "summer"

    return "autumn"


# ==========================================================
# BASE TEMPERATURE
# ==========================================================

def get_base_temperature(
    city: str,
    month: int
):

    season = get_season(month)

    return CITY_CLIMATE[city][season]


# ==========================================================
# DAILY TEMPERATURE CURVE
# ==========================================================

def get_hourly_adjustment(
    hour: int
):

    # Coldest hours
    if 0 <= hour <= 5:
        return -4

    # Morning
    elif 6 <= hour <= 9:
        return -1

    # Hottest hours
    elif 10 <= hour <= 15:
        return 3

    # Afternoon
    elif 16 <= hour <= 18:
        return 1

    # Evening
    return -2


# ==========================================================
# TEMPERATURE GENERATOR
# ==========================================================

def generate_temperature(
    city: str,
    month: int,
    hour: int
):

    base_temp = get_base_temperature(
        city,
        month
    )

    hourly_adjustment = get_hourly_adjustment(
        hour
    )

    weather_noise = random.uniform(
        -2,
        2
    )

    temperature = (
        base_temp
        + hourly_adjustment
        + weather_noise
    )

    # Prevent unrealistic extremes
    temperature = max(
        8,
        min(48, temperature)
    )

    return round(
        temperature,
        1
    )


# ==========================================================
# WEATHER CONDITION
# ==========================================================

def generate_weather_condition(
    city: str,
    temperature: float
):

    # Extreme Heat
    if temperature >= 42:
        return "Hot"

    # Cold Weather
    if temperature <= 12:
        return "Cold"

    # Alexandria tends to be cloudier
    if city == "Alexandria":

        choices = [
            "Sunny",
            "Partly Cloudy",
            "Cloudy",
            "Windy"
        ]

        weights = [
            35,
            25,
            30,
            10
        ]

    else:

        choices = [
            "Sunny",
            "Clear",
            "Partly Cloudy",
            "Windy"
        ]

        weights = [
            60,
            20,
            15,
            5
        ]

    return random.choices(
        choices,
        weights=weights,
        k=1
    )[0]


# ==========================================================
# WEATHER IMPACT FACTOR
# Used later in visitor generation
# ==========================================================

def get_weather_factor(
    temperature: float
):

    if temperature > 44:
        return 0.70

    elif temperature > 40:
        return 0.85

    elif temperature > 35:
        return 0.95

    elif temperature < 10:
        return 0.80

    return 1.00
# ==========================================================
# MASTER WEATHER ENGINE
# ==========================================================

def generate_weather(
    city: str,
    month: int,
    hour: int
):

    temperature = generate_temperature(
        city,
        month,
        hour
    )

    weather_condition = (
        generate_weather_condition(
            city,
            temperature
        )
    )

    weather_factor = get_weather_factor(
        temperature
    )

    return {
    "temperature_c": temperature,
    "weather_condition": weather_condition,
    "weather_factor": weather_factor,
    "is_real_weather": False
}

"""
historical_events_engine.py
"""

import pandas as pd

EVENTS_FILE = "holidays_events.csv"

events_df = pd.read_csv(EVENTS_FILE)


def get_event_info(
    timestamp,
    city
):

    month = timestamp.month
    day = timestamp.day

    for _, event in events_df.iterrows():

        start = pd.to_datetime(
            event["start_date"]
        )

        end = pd.to_datetime(
            event["end_date"]
        )

        start_month_day = (
            start.month,
            start.day
        )

        end_month_day = (
            end.month,
            end.day
        )

        current_month_day = (
            month,
            day
        )

        city_match = (
            city in str(
                event["cities_affected"]
            )
            or
            "Nationwide"
            in str(
                event["cities_affected"]
            )
        )

        if not city_match:
            continue

        if (
            start_month_day
            <= current_month_day
            <= end_month_day
        ):

            duration = (
                end - start
            ).days + 1

            return {

                "is_holiday": True,

                "event_name":
                    event["event_name"],

                "event_type":
                    event["event_type"],

                "visitor_multiplier":
                    float(
                        event[
                            "visitor_multiplier"
                        ]
                    ),

                "school_vacation":
                    bool(
                        event[
                            "school_vacation"
                        ]
                    ),

                "tourism_season":
                    bool(
                        event[
                            "tourism_season"
                        ]
                    ),

                "event_duration_days":
                    duration
            }

    return {

        "is_holiday": False,

        "event_name": None,

        "event_type": None,

        "visitor_multiplier": 1.0,

        "school_vacation": False,

        "tourism_season": False,

        "event_duration_days": 0
    }

"""
historical_generator.py
Spirit of Ankh - Historical Dataset Generator V1.1

Generates:
- historical_2023.csv
- historical_2024.csv
- historical_2025.csv

- historical_2023.parquet
- historical_2024.parquet
- historical_2025.parquet

Dependencies:
-------------
historical_rules.py
historical_weather.py
historical_events_engine.py

Input:
------
core_locations.csv
holidays_events.csv
"""

import random
import pandas as pd

# from historical_rules import (
#     get_context_score,
#     get_crowd_status,
#     is_weekend,
#     get_school_vacation
# )

# from historical_weather import (
#     generate_weather
# )

# from historical_events_engine import (
#     get_event_info
# )


# ==========================================================
# CONFIG
# ==========================================================

LOCATIONS_FILE = "core_locations.csv"

BASE_UTILIZATION = {
    "Tier1": 0.45,
    "Tier2": 0.30,
    "Tier3": 0.20
}


# ==========================================================
# LOAD LOCATIONS
# ==========================================================

locations_df = pd.read_csv(
    LOCATIONS_FILE
)


# ==========================================================
# HOUR FACTOR
# ==========================================================

def get_hour_factor(
    hour,
    opening_hour,
    closing_hour
):

    if hour < opening_hour:
        return 0

    if hour >= closing_hour:
        return 0

    operating_hours = (
        closing_hour
        - opening_hour
    )

    progress = (
        hour
        - opening_hour
    ) / operating_hours

    if progress < 0.20:
        return 0.60

    elif progress < 0.40:
        return 0.90

    elif progress < 0.70:
        return 1.30

    elif progress < 0.90:
        return 1.00

    return 0.70


# ==========================================================
# VISITOR GENERATOR
# ==========================================================

def generate_visitor_count(
    row,
    context,
    weather,
    hour_factor
):

    base_visitors = (
        row["max_capacity"]
        * BASE_UTILIZATION[
            row["popularity_tier"]
        ]
    )

    popularity_factor = (
        row["popularity_weight"]
    )

    weather_factor = (
        weather["weather_factor"]
    )

    noise = random.gauss(
        1.0,
        0.08
    )

    visitor_count = (
        base_visitors
        * popularity_factor
        * hour_factor
        * context["total_multiplier"]
        * weather_factor
        * noise
    )

    visitor_count = max(
        0,
        int(visitor_count)
    )

    visitor_count = min(
        visitor_count,
        int(row["max_capacity"])
    )

    return visitor_count


# ==========================================================
# GENERATE YEAR
# ==========================================================

def generate_year_dataset(year):

    records = []

    timestamps = pd.date_range(
        start=f"{year}-01-01 00:00:00",
        end=f"{year}-12-31 23:00:00",
        freq="h"
    )

    print(
        f"Generating {year}..."
    )

    for timestamp in timestamps:

        school_vacation, _ = (
            get_school_vacation(
                timestamp.month
            )
        )

        for _, row in (
            locations_df.iterrows()
        ):

            hour_factor = (
                get_hour_factor(
                    timestamp.hour,
                    row["opening_hour"],
                    row["closing_hour"]
                )
            )

            if hour_factor == 0:
                continue

            event_info = (
                get_event_info(
                    timestamp,
                    row["city"]
                )
            )

            context = (
                get_context_score(
                    city=row["city"],
                    timestamp=timestamp,
                    is_holiday=event_info["is_holiday"],
                    holiday_type=event_info["event_type"],
                    event_multiplier=event_info[
                        "visitor_multiplier"
                    ]
                )
            )

            weather = (
                generate_weather(
                    city=row["city"],
                    month=timestamp.month,
                    hour=timestamp.hour
                )
            )

            visitor_count = (
                generate_visitor_count(
                    row,
                    context,
                    weather,
                    hour_factor
                )
            )

            occupancy_rate = round(
                visitor_count
                / row["max_capacity"],
                3
            )

            crowd_status = (
                get_crowd_status(
                    occupancy_rate
                )
            )

            records.append({

                "timestamp":
                    timestamp,

                "date":
                    timestamp.date(),

                "year":
                    timestamp.year,

                "month":
                    timestamp.month,

                "day":
                    timestamp.day,

                "hour":
                    timestamp.hour,

                "location_id":
                    row["location_id"],

                "location_name":
                    row["location_name"],

                "city":
                    row["city"],

                "location_type":
                    row["location_type"],

                "latitude":
                    row["latitude"],

                "longitude":
                    row["longitude"],

                "opening_hour":
                    row["opening_hour"],

                "closing_hour":
                    row["closing_hour"],

                "popularity_tier":
                    row["popularity_tier"],

                "popularity_weight":
                    row["popularity_weight"],

                "max_capacity":
                    row["max_capacity"],

                "visitor_count":
                    visitor_count,

                "occupancy_rate":
                    occupancy_rate,

                "crowd_status":
                    crowd_status,

                "temperature_c":
                    weather["temperature_c"],

                "weather_condition":
                    weather["weather_condition"],

                "weather_factor":
                    weather["weather_factor"],

                "is_real_weather":
                    weather["is_real_weather"],

                "special_event":
                    event_info["event_name"],

                "event_type":
                    event_info["event_type"],

                "event_duration_days":
                    event_info[
                        "event_duration_days"
                    ],

                "is_weekend":
                    is_weekend(timestamp),

                "is_holiday":
                    event_info["is_holiday"],

                "holiday_overlap":
                    (
                        event_info[
                            "is_holiday"
                        ]
                        and school_vacation
                    ),

                "school_vacation":
                    school_vacation,

                "tourism_season":
                    context[
                        "tourism_season"
                    ],

                "data_source":
                    "historical_simulation"
            })

    dataset = pd.DataFrame(
        records
    )

    csv_file = (
        f"historical_{year}.csv"
    )

    parquet_file = (
        f"historical_{year}.parquet"
    )

    dataset.to_csv(
        csv_file,
        index=False
    )

    dataset.to_parquet(
        parquet_file,
        index=False
    )

    print(
        f"Saved: {csv_file}"
    )

    print(
        f"Saved: {parquet_file}"
    )

    print(
        f"Rows: {len(dataset):,}"
    )


# ==========================================================
# MAIN
# ==========================================================

if __name__ == "__main__":

    generate_year_dataset(2023)

    generate_year_dataset(2024)

    generate_year_dataset(2025)

    print(
        "Historical Dataset Generation Complete."
    )