# -*- coding: utf-8 -*-
"""historical_weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ou8pLZejdZCw_-U53TGM2cRCiGPEW82
"""

"""
historical_weather.py
Spirit of Ankh - Historical Weather Engine

Generates realistic simulated weather
for Egyptian tourism locations.

Output:
--------
temperature_c
weather_condition
is_real_weather=False
"""

import random

# ==========================================================
# CITY CLIMATE PROFILES
# Seasonal Average Temperatures (°C)
# ==========================================================

CITY_CLIMATE = {

    "Cairo": {
        "winter": 18,
        "spring": 27,
        "summer": 36,
        "autumn": 28
    },

    "Giza": {
        "winter": 18,
        "spring": 28,
        "summer": 37,
        "autumn": 29
    },

    "Alexandria": {
        "winter": 16,
        "spring": 23,
        "summer": 30,
        "autumn": 24
    },

    "Luxor": {
        "winter": 22,
        "spring": 34,
        "summer": 43,
        "autumn": 35
    },

    "Aswan": {
        "winter": 24,
        "spring": 36,
        "summer": 45,
        "autumn": 37
    },

    "Sharm El Sheikh": {
        "winter": 22,
        "spring": 30,
        "summer": 38,
        "autumn": 31
    },

    "Hurghada": {
        "winter": 21,
        "spring": 31,
        "summer": 37,
        "autumn": 30
    },

    "Dahab": {
        "winter": 20,
        "spring": 29,
        "summer": 35,
        "autumn": 29
    },

    "Fayoum": {
        "winter": 17,
        "spring": 28,
        "summer": 39,
        "autumn": 29
    }
}


# ==========================================================
# SEASON DETECTION
# ==========================================================

def get_season(month: int):

    if month in [12, 1, 2]:
        return "winter"

    elif month in [3, 4, 5]:
        return "spring"

    elif month in [6, 7, 8]:
        return "summer"

    return "autumn"


# ==========================================================
# BASE TEMPERATURE
# ==========================================================

def get_base_temperature(
    city: str,
    month: int
):

    season = get_season(month)

    return CITY_CLIMATE[city][season]


# ==========================================================
# DAILY TEMPERATURE CURVE
# ==========================================================

def get_hourly_adjustment(
    hour: int
):

    # Coldest hours
    if 0 <= hour <= 5:
        return -4

    # Morning
    elif 6 <= hour <= 9:
        return -1

    # Hottest hours
    elif 10 <= hour <= 15:
        return 3

    # Afternoon
    elif 16 <= hour <= 18:
        return 1

    # Evening
    return -2


# ==========================================================
# TEMPERATURE GENERATOR
# ==========================================================

def generate_temperature(
    city: str,
    month: int,
    hour: int
):

    base_temp = get_base_temperature(
        city,
        month
    )

    hourly_adjustment = get_hourly_adjustment(
        hour
    )

    weather_noise = random.uniform(
        -2,
        2
    )

    temperature = (
        base_temp
        + hourly_adjustment
        + weather_noise
    )

    # Prevent unrealistic extremes
    temperature = max(
        8,
        min(48, temperature)
    )

    return round(
        temperature,
        1
    )


# ==========================================================
# WEATHER CONDITION
# ==========================================================

def generate_weather_condition(
    city: str,
    temperature: float
):

    # Extreme Heat
    if temperature >= 42:
        return "Hot"

    # Cold Weather
    if temperature <= 12:
        return "Cold"

    # Alexandria tends to be cloudier
    if city == "Alexandria":

        choices = [
            "Sunny",
            "Partly Cloudy",
            "Cloudy",
            "Windy"
        ]

        weights = [
            35,
            25,
            30,
            10
        ]

    else:

        choices = [
            "Sunny",
            "Clear",
            "Partly Cloudy",
            "Windy"
        ]

        weights = [
            60,
            20,
            15,
            5
        ]

    return random.choices(
        choices,
        weights=weights,
        k=1
    )[0]


# ==========================================================
# WEATHER IMPACT FACTOR
# Used later in visitor generation
# ==========================================================

def get_weather_factor(
    temperature: float
):

    if temperature > 44:
        return 0.70

    elif temperature > 40:
        return 0.85

    elif temperature > 35:
        return 0.95

    elif temperature < 10:
        return 0.80

    return 1.00
# ==========================================================
# MASTER WEATHER ENGINE
# ==========================================================

def generate_weather(
    city: str,
    month: int,
    hour: int
):

    temperature = generate_temperature(
        city,
        month,
        hour
    )

    weather_condition = (
        generate_weather_condition(
            city,
            temperature
        )
    )

    weather_factor = get_weather_factor(
        temperature
    )

    return {
    "temperature_c": temperature,
    "weather_condition": weather_condition,
    "weather_factor": weather_factor,
    "is_real_weather": False
}

# from historical_weather import *

print(generate_weather("Cairo", 1, 14))
print(generate_weather("Cairo", 7, 14))
print(generate_weather("Alexandria", 7, 14))
print(generate_weather("Aswan", 7, 14))