# -*- coding: utf-8 -*-
"""historical_events_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9lGI9uIbNI8isane_q7T4ct4sQgAz6B
"""

"""
historical_events_engine.py
"""

import pandas as pd

EVENTS_FILE = "holidays_events.csv"

events_df = pd.read_csv(EVENTS_FILE)


def get_event_info(
    timestamp,
    city
):

    month = timestamp.month
    day = timestamp.day

    for _, event in events_df.iterrows():

        start = pd.to_datetime(
            event["start_date"]
        )

        end = pd.to_datetime(
            event["end_date"]
        )

        start_month_day = (
            start.month,
            start.day
        )

        end_month_day = (
            end.month,
            end.day
        )

        current_month_day = (
            month,
            day
        )

        city_match = (
            city in str(
                event["cities_affected"]
            )
            or
            "Nationwide"
            in str(
                event["cities_affected"]
            )
        )

        if not city_match:
            continue

        if (
            start_month_day
            <= current_month_day
            <= end_month_day
        ):

            duration = (
                end - start
            ).days + 1

            return {

                "is_holiday": True,

                "event_name":
                    event["event_name"],

                "event_type":
                    event["event_type"],

                "visitor_multiplier":
                    float(
                        event[
                            "visitor_multiplier"
                        ]
                    ),

                "school_vacation":
                    bool(
                        event[
                            "school_vacation"
                        ]
                    ),

                "tourism_season":
                    bool(
                        event[
                            "tourism_season"
                        ]
                    ),

                "event_duration_days":
                    duration
            }

    return {

        "is_holiday": False,

        "event_name": None,

        "event_type": None,

        "visitor_multiplier": 1.0,

        "school_vacation": False,

        "tourism_season": False,

        "event_duration_days": 0
    }

# from historical_events_engine import *

print(
    get_event_info(
        pd.Timestamp(
            "2024-03-21"
        ),
        "Cairo"
    )
)