# -*- coding: utf-8 -*-
"""historical_rules.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YwEPQ5Xcc21DmrSCSG7rbye4D8m69a86
"""

"""
historical_rules.py
Spirit of Ankh - Historical Tourism Dataset Generator

Centralized business rules for:
- Tourism seasons
- School vacations
- Holidays
- Events
- Weekend effects
- Crowd status
- Context multipliers
"""

from datetime import datetime

# ==========================================================
# TOURISM SEASONS BY CITY
# ==========================================================

TOURISM_SEASONS = {

    "Cairo": {
        "Peak": [11, 12, 1, 2],
        "High": [3, 4, 10],
        "Normal": [5, 9],
        "Low": [6, 7, 8]
    },

    "Giza": {
        "Peak": [11, 12, 1, 2],
        "High": [3, 4, 10],
        "Normal": [5, 9],
        "Low": [6, 7, 8]
    },

    "Luxor": {
        "Peak": [11, 12, 1, 2],
        "High": [3, 4, 10],
        "Normal": [5, 9],
        "Low": [6, 7, 8]
    },

    "Aswan": {
        "Peak": [11, 12, 1, 2],
        "High": [3, 4, 10],
        "Normal": [5, 9],
        "Low": [6, 7, 8]
    },

    "Alexandria": {
        "Peak": [6, 7, 8],
        "High": [5, 9],
        "Normal": [4, 10],
        "Low": [11, 12, 1, 2, 3]
    },

    "Hurghada": {
        "Peak": [6, 7, 8, 12, 1],
        "High": [4, 5, 9, 10],
        "Normal": [2, 3, 11],
        "Low": []
    },

    "Sharm El Sheikh": {
        "Peak": [6, 7, 8, 12, 1],
        "High": [4, 5, 9, 10],
        "Normal": [2, 3, 11],
        "Low": []
    },

    "Dahab": {
        "Peak": [6, 7, 8],
        "High": [4, 5, 9, 10],
        "Normal": [11, 12, 1, 2, 3],
        "Low": []
    },

    "Fayoum": {
        "Peak": [10, 11, 12, 1, 2, 3],
        "High": [4, 5],
        "Normal": [9],
        "Low": [6, 7, 8]
    }
}


# ==========================================================
# SEASON MULTIPLIERS
# ==========================================================

SEASON_MULTIPLIERS = {
    "Peak": 1.50,
    "High": 1.25,
    "Normal": 1.00,
    "Low": 0.75
}


# ==========================================================
# CITY TOURISM WEIGHT
# Used later in visitor generation
# ==========================================================




# ==========================================================
# SCHOOL VACATIONS
# ==========================================================

SUMMER_VACATION_MONTHS = [6, 7, 8]

MIDYEAR_VACATION_MONTHS = [1]

VACATION_MULTIPLIERS = {
    "summer": 1.25,
    "midyear": 1.15,
    "none": 1.00
}


# ==========================================================
# WEEKEND
# Egypt: Friday + Saturday
# ==========================================================

WEEKEND_MULTIPLIER = 1.15


# ==========================================================
# HOLIDAY MULTIPLIERS
# ==========================================================

HOLIDAY_MULTIPLIERS = {

    "National Holiday": 1.15,

    "Religious Holiday": 1.30,

    "Eid Al Fitr": 1.50,

    "Eid Al Adha": 1.60,

    "Christmas": 1.10,

    "New Year": 1.10,

    "Event": 1.20,

    "Regular": 1.00
}




# ==========================================================
# CROWD STATUS
# ==========================================================

def get_crowd_status(occupancy_rate: float) -> str:

    if occupancy_rate >= 0.90:
        return "Overcrowded"

    elif occupancy_rate >= 0.70:
        return "Busy"

    elif occupancy_rate >= 0.40:
        return "Moderate"

    return "Low"


# ==========================================================
# CITY WEIGHT
# ==========================================================




# ==========================================================
# TOURISM SEASON
# ==========================================================

def get_tourism_season(city: str, month: int) -> str:

    city_rules = TOURISM_SEASONS.get(city)

    if not city_rules:
        return "Normal"

    for season_name, months in city_rules.items():

        if month in months:
            return season_name

    return "Normal"


# ==========================================================
# SEASON MULTIPLIER
# ==========================================================

def get_season_multiplier(city: str, month: int) -> float:

    season = get_tourism_season(city, month)

    return SEASON_MULTIPLIERS.get(season, 1.0)


# ==========================================================
# SCHOOL VACATION
# ==========================================================

def get_school_vacation(month: int):

    if month in SUMMER_VACATION_MONTHS:
        return True, "summer"

    if month in MIDYEAR_VACATION_MONTHS:
        return True, "midyear"

    return False, "none"


def get_vacation_multiplier(month: int):

    _, vacation_type = get_school_vacation(month)

    return VACATION_MULTIPLIERS[vacation_type]


# ==========================================================
# WEEKEND
# ==========================================================

def is_weekend(timestamp: datetime) -> bool:

    return timestamp.weekday() in [4, 5]


def get_weekend_multiplier(timestamp: datetime):

    if is_weekend(timestamp):
        return WEEKEND_MULTIPLIER

    return 1.0


# ==========================================================
# HOLIDAY MULTIPLIER
# ==========================================================

def get_holiday_multiplier(
    is_holiday: bool,
    holiday_type: str = "Regular"
):

    if not is_holiday:
        return 1.0

    return HOLIDAY_MULTIPLIERS.get(
        holiday_type,
        1.15
    )


# ==========================================================
# EVENT MULTIPLIER
# ==========================================================



# ==========================================================
# MASTER CONTEXT ENGINE
# ==========================================================

def get_context_score(
    city: str,
    timestamp: datetime,
    is_holiday: bool = False,
    holiday_type: str = "Regular",
    event_multiplier: float = 1.0
):

    month = timestamp.month

    season_multiplier = get_season_multiplier(
        city,
        month
    )

    vacation_multiplier = get_vacation_multiplier(
        month
    )

    weekend_multiplier = get_weekend_multiplier(
        timestamp
    )

    holiday_multiplier = get_holiday_multiplier(
        is_holiday,
        holiday_type
    )

    event_multiplier = 1.0

    total_multiplier = (
    season_multiplier
    * vacation_multiplier
    * weekend_multiplier
    * holiday_multiplier
    * event_multiplier
)

    # Prevent unrealistic explosion
    total_multiplier = min(
        total_multiplier,
        2.50
    )

    return {

        "tourism_season": get_tourism_season(
            city,
            month
        ),

        "season_multiplier": season_multiplier,

        "vacation_multiplier": vacation_multiplier,

        "weekend_multiplier": weekend_multiplier,

        "holiday_multiplier": holiday_multiplier,

        "event_multiplier": event_multiplier,



        "total_multiplier": round(
            total_multiplier,
            3
        )
    }

from datetime import datetime
# from historical_rules import *

# ==================================================
# Test 1
# Luxor Winter
# ==================================================

dt = datetime(2024, 1, 15, 12)

print("\n===== TEST 1 =====")

result = get_context_score(
    city="Luxor",
    timestamp=dt,
    is_holiday=False,
    holiday_type="Regular",
    event_type="None"
)

print(result)

# ==================================================
# Test 2
# Alexandria Summer
# ==================================================

dt = datetime(2024, 7, 10, 14)

print("\n===== TEST 2 =====")

result = get_context_score(
    city="Alexandria",
    timestamp=dt
)

print(result)

# ==================================================
# Test 3
# Eid in Giza
# ==================================================

dt = datetime(2024, 4, 11, 18)

print("\n===== TEST 3 =====")

result = get_context_score(
    city="Giza",
    timestamp=dt,
    is_holiday=True,
    holiday_type="Eid Al Fitr",
    event_type="Festival"
)

print(result)

# ==================================================
# Test 4
# Weekend Detection
# ==================================================

print("\n===== TEST 4 =====")

friday = datetime(2024, 6, 21)
monday = datetime(2024, 6, 24)

print("Friday:", is_weekend(friday))
print("Monday:", is_weekend(monday))

# ==================================================
# Test 5
# Crowd Status
# ==================================================

print("\n===== TEST 5 =====")

for value in [0.25, 0.50, 0.80, 0.95]:
    print(value, "->", get_crowd_status(value))