# -*- coding: utf-8 -*-
"""event_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mHZNfnHndRu9W6uUIvLZF62yFpbTnC7
"""

import pandas as pd

# ==========================================
# LOAD EVENTS DATASET
# ==========================================

def load_events(file_path):

    events = pd.read_csv(file_path)

    events["start_date"] = pd.to_datetime(
        events["start_date"]
    )

    events["end_date"] = pd.to_datetime(
        events["end_date"]
    )

    return events


# ==========================================
# GET ACTIVE EVENTS
# ==========================================

def get_active_events(
    events_df,
    current_date
):

    current_date = pd.to_datetime(
        current_date
    )

    active_events = events_df[
        (events_df["start_date"] <= current_date)
        &
        (events_df["end_date"] >= current_date)
    ]

    return active_events


# ==========================================
# GET CITY EVENTS
# ==========================================

def get_city_events(
    active_events,
    city
):

    city_events = active_events[
        active_events[
            "cities_affected"
        ].str.contains(
            city,
            case=False,
            na=False
        )
    ]

    nationwide_events = active_events[
        active_events[
            "cities_affected"
        ].str.contains(
            "Nationwide",
            case=False,
            na=False
        )
    ]

    return pd.concat(
        [
            city_events,
            nationwide_events
        ]
    ).drop_duplicates()


# ==========================================
# PRIMARY EVENT
# ==========================================

def get_primary_event(
    city_events
):

    if city_events.empty:

        return {

            "event_name": None,

            "event_type": None,

            "priority": 0
        }

    primary_event = (
        city_events
        .sort_values(
            by="priority",
            ascending=False
        )
        .iloc[0]
    )

    return {

        "event_name":
            primary_event["event_name"],

        "event_type":
            primary_event["event_type"],

        "priority":
            primary_event["priority"]
    }


# ==========================================
# EVENT MULTIPLIER
# ==========================================

def get_event_multiplier(
    city_events
):

    if city_events.empty:
        return 1.0

    total_boost = 0

    for _, row in city_events.iterrows():

        total_boost += (
            row["visitor_multiplier"] - 1
        )

    final_multiplier = (
        1 + total_boost
    )

    return round(
        min(final_multiplier, 3.0),
        2
    )


# ==========================================
# HOLIDAY OVERLAP
# ==========================================

def calculate_holiday_overlap(
    city_events
):

    return max(
        len(city_events) - 1,
        0
    )


# ==========================================
# SCHOOL VACATION FLAG
# ==========================================

def is_school_vacation(
    city_events
):

    if city_events.empty:
        return 0

    return int(

        (
            city_events[
                "school_vacation"
            ] == 1

        ).any()
    )


# ==========================================
# TOURISM SEASON FLAG
# ==========================================

def is_tourism_season(
    city_events
):

    if city_events.empty:
        return 0

    return int(

        (
            city_events[
                "tourism_season"
            ] == 1

        ).any()
    )