# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_OMxZG5CjFUaQVsHWgV1rsy9J-tdfRo
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ==========================================
# SYSTEM CONFIGURATION
# ==========================================

INTERVAL_SECONDS = 600

# ==========================================
# OPENWEATHER API
# ==========================================

OPENWEATHER_API_KEY = os.getenv(
    "OPENWEATHER_API_KEY"
)

# ==========================================
# FILE PATHS
# ==========================================

CORE_LOCATIONS_FILE = "data/core_locations.csv"
HOLIDAYS_EVENTS_FILE = "data/holidays_events.csv"

# ==========================================
# HOURLY FACTORS
# ==========================================

HOURLY_FACTORS = {
    "early_morning": 0.40,
    "peak_hours": 1.20,
    "afternoon": 0.90,
    "evening": 0.70,
    "night": 0.20
}

# ==========================================
# WEEKEND FACTORS
# ==========================================

FRIDAY_FACTOR = 1.25
SATURDAY_FACTOR = 1.20
DEFAULT_DAY_FACTOR = 1.00

# ==========================================
# WEATHER FACTORS
# ==========================================

TEMPERATURE_FACTORS = {
    "ideal": 1.00,      # 20-30°C
    "warm": 0.90,       # 30-35°C
    "hot": 0.75,        # 35-40°C
    "extreme": 0.60     # >40°C
}

WEATHER_CONDITION_FACTORS = {
    "Clear": 1.00,
    "Cloudy": 0.95,
    "Windy": 0.90,
    "Rain": 0.70,
    "Storm": 0.50
}

# ==========================================
# RANDOMIZATION
# ==========================================

RANDOM_MIN = 0.92
RANDOM_MAX = 1.08

# ==========================================
# CROWD LEVEL THRESHOLDS
# ==========================================

LOW_THRESHOLD = 0.30
MEDIUM_THRESHOLD = 0.60
HIGH_THRESHOLD = 0.85

# ==========================================
# RESOURCE MAPPING
# ==========================================

RESOURCE_MAPPING = {
    "Low": "Low",
    "Medium": "Medium",
    "High": "High",
    "Critical": "Emergency"
}

# ==========================================
# DEFAULT WEATHER FALLBACK
# ==========================================

DEFAULT_TEMPERATURE = 25
DEFAULT_HUMIDITY = 50
DEFAULT_CONDITION = "Clear"

# ==========================================
# SNOWFLAKE CONFIG
# ==========================================

SF_USER = os.getenv("SF_USER")
SF_PASSWORD = os.getenv("SF_PASSWORD")
SF_ACCOUNT = os.getenv("SF_ACCOUNT")

SF_WAREHOUSE = "TOURISM_WH"
SF_DATABASE = "TOURISM_DB"
SF_SCHEMA = "RAW_DATA"

SF_TABLE = "TOURISM_LIVE_RAW"