# -*- coding: utf-8 -*-
"""sensor_simulator.ipynb

import os

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EoSbM5LFUEqgNk-anYi0J9PrGuZKfq2O
"""
import os
import pandas as pd
from datetime import datetime

from config import (
    CORE_LOCATIONS_FILE,
    HOLIDAYS_EVENTS_FILE
)

from weather_engine import (
    get_all_cities_weather,
    get_weather_factor
)

from event_engine import (
    load_events,
    get_active_events,
    get_city_events,
    get_primary_event,
    get_event_multiplier,
    calculate_holiday_overlap,
    is_school_vacation,
    is_tourism_season
)

from crowd_engine import (
    get_hour_factor,
    generate_visitor_count,
    calculate_crowd_density,
    get_crowd_level,
    get_resource_usage,
    calculate_noise_level,
    calculate_satisfaction_score,
    get_peak_flag
)


# ==========================================
# BUILD CITY REFERENCE
# ==========================================

def build_city_reference(locations_df):

    city_reference = {}

    for city in locations_df["city"].unique():

        city_row = locations_df[
            locations_df["city"] == city
        ].iloc[0]

        city_reference[city] = (
            city_row["latitude"],
            city_row["longitude"]
        )

    return city_reference


# ==========================================
# OPEN / CLOSED CHECK
# ==========================================

def is_location_open(
    current_hour,
    opening_hour,
    closing_hour
):

    if opening_hour < closing_hour:

        return (
            opening_hour <= current_hour < closing_hour
        )

    return (
        current_hour >= opening_hour
        or current_hour < closing_hour
    )


# ==========================================
# MAIN SENSOR FUNCTION
# ==========================================

def generate_sensor_data():

    locations_df = pd.read_csv(
    os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "core_locations.csv")
)

    city_reference = build_city_reference(
        locations_df
    )

    events = load_events(
        HOLIDAYS_EVENTS_FILE
    )

    current_datetime = datetime.now()

    today = current_datetime.strftime(
        "%Y-%m-%d"
    )

    current_hour = current_datetime.hour

    day_of_week = current_datetime.strftime(
        "%A"
    )

    is_weekend = int(
        current_datetime.weekday() in [4, 5]
    )

    active_events = get_active_events(
        events,
        today
    )

    weather_data = get_all_cities_weather(
        city_reference
    )

    records = []

    for _, location in locations_df.iterrows():

        city = location["city"]

        # ==========================================
        # WEATHER
        # ==========================================

        weather = weather_data.get(
            city,
            {
                "temperature_c": 25,
                "humidity": 50,
                "weather_condition": "Clear"
            }
        )

        weather_factor = get_weather_factor(
            weather
        )

        # ==========================================
        # EVENTS
        # ==========================================

        city_events = get_city_events(
            active_events,
            city
        )

        primary_event = get_primary_event(
            city_events
        )

        event_multiplier = get_event_multiplier(
            city_events
        )

        # ==========================================
        # OPEN STATUS
        # ==========================================

        location_open = is_location_open(
            current_hour,
            location["opening_hour"],
            location["closing_hour"]
        )

        # ==========================================
        # VISITOR COUNT
        # ==========================================

        if location_open:

            visitor_count = generate_visitor_count(
                max_capacity=location["max_capacity"],
                popularity_weight=location["popularity_weight"],
                weather_factor=weather_factor,
                event_multiplier=event_multiplier,
                hour_factor=get_hour_factor(
                    current_hour
                )
            )

        else:

            visitor_count = 0

        # ==========================================
        # CROWD METRICS
        # ==========================================

        crowd_density = calculate_crowd_density(
            visitor_count,
            location["max_capacity"]
        )

        crowd_level = get_crowd_level(
            crowd_density
        )

        noise_level = calculate_noise_level(
            crowd_density
        )

        peak_flag = get_peak_flag(
            crowd_density
        )

        # ==========================================
        # SATISFACTION
        # ==========================================

        if visitor_count == 0:

            satisfaction_score = None

        else:

            satisfaction_score = (
                calculate_satisfaction_score(
                    crowd_density
                )
            )

        # ==========================================
        # RECORD
        # ==========================================

        records.append({

            "timestamp":
                current_datetime.isoformat(),

            "simulation_hour":
                current_hour,

            "day_of_week":
                day_of_week,

            "is_weekend":
                is_weekend,

            "location_id":
                location["location_id"],

            "location_name":
                location["location_name"],

            "city":
                city,

            "location_type":
                location["location_type"],

            "latitude":
                location["latitude"],

            "longitude":
                location["longitude"],

            "is_open":
                int(location_open),

            "opening_hour":
                location["opening_hour"],

            "closing_hour":
                location["closing_hour"],

            "visitor_count":
                visitor_count,

            "crowd_density":
                crowd_density,

            "crowd_level":
                crowd_level,

            "temperature_c":
                weather["temperature_c"],

            "humidity":
                weather["humidity"],

            "weather_condition":
                weather["weather_condition"],

            "weather_factor":
                weather_factor,

            "event_name":
                primary_event["event_name"],

            "event_type":
                primary_event["event_type"],

            "event_multiplier":
                event_multiplier,

            "holiday_overlap":
                calculate_holiday_overlap(
                    city_events
                ),

            "school_vacation":
                is_school_vacation(
                    city_events
                ),

            "tourism_season":
                is_tourism_season(
                    city_events
                ),

            "resource_usage":
                get_resource_usage(
                    crowd_level
                ),

            "noise_level_db":
                noise_level,

            "satisfaction_score":
                satisfaction_score,

            "peak_flag":
                peak_flag
        })

    sensor_df = pd.DataFrame(
        records
    )

    return sensor_df


# ==========================================
# RUN SCRIPT
# ==========================================

if __name__ == "__main__":

    sensor_df = generate_sensor_data()

    print(
        f"Generated Records: {len(sensor_df)}"
    )

    sensor_df.to_csv(
        "output/tourism_sensor_data.csv",
        index=False
    )

    print(
        "tourism_sensor_data.csv saved successfully."
    )
