# -*- coding: utf-8 -*-
"""weather_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCDXUvNujMIvH3uisbdCQ-tCExMS9MCF
"""

import requests

from config import (
    OPENWEATHER_API_KEY,
    DEFAULT_TEMPERATURE,
    DEFAULT_HUMIDITY,
    DEFAULT_CONDITION,
    TEMPERATURE_FACTORS,
    WEATHER_CONDITION_FACTORS
)

# ==========================================
# WEATHER CONDITION NORMALIZATION
# ==========================================

def normalize_weather_condition(condition):

    mapping = {
        "Clear": "Clear",
        "Clouds": "Cloudy",
        "Mist": "Cloudy",
        "Fog": "Cloudy",
        "Haze": "Cloudy",
        "Smoke": "Cloudy",
        "Dust": "Cloudy",
        "Sand": "Cloudy",
        "Drizzle": "Rain",
        "Rain": "Rain",
        "Thunderstorm": "Storm",
        "Squall": "Windy",
        "Tornado": "Storm"
    }

    return mapping.get(condition, "Clear")


# ==========================================
# TEMPERATURE FACTOR
# ==========================================

def get_temperature_factor(temp):

    if 20 <= temp <= 30:
        return TEMPERATURE_FACTORS["ideal"]

    elif 30 < temp <= 35:
        return TEMPERATURE_FACTORS["warm"]

    elif 35 < temp <= 40:
        return TEMPERATURE_FACTORS["hot"]

    return TEMPERATURE_FACTORS["extreme"]


# ==========================================
# WEATHER FACTOR
# ==========================================

def get_weather_factor(weather):

    temperature = weather["temperature_c"]

    temp_factor = get_temperature_factor(
        temperature
    )

    condition_factor = (
        WEATHER_CONDITION_FACTORS.get(
            weather["weather_condition"],
            1.0
        )
    )

    return round(
        temp_factor * condition_factor,
        2
    )


# ==========================================
# GET WEATHER FOR ONE CITY
# ==========================================

def get_city_weather(lat, lon):

    url = (
        "https://api.openweathermap.org/data/2.5/weather"
        f"?lat={lat}"
        f"&lon={lon}"
        f"&appid={OPENWEATHER_API_KEY}"
        f"&units=metric"
    )

    try:

        response = requests.get(
            url,
            timeout=10
        )

        response.raise_for_status()

        data = response.json()

        return {

            "temperature_c":
                round(
                    data["main"]["temp"],
                    2
                ),

            "humidity":
                data["main"]["humidity"],

            "weather_condition":
                normalize_weather_condition(
                    data["weather"][0]["main"]
                )
        }

    except Exception as e:

        print(
            f"[Weather Error] "
            f"lat={lat}, lon={lon} -> {e}"
        )

        return {

            "temperature_c":
                DEFAULT_TEMPERATURE,

            "humidity":
                DEFAULT_HUMIDITY,

            "weather_condition":
                DEFAULT_CONDITION
        }


# ==========================================
# GET WEATHER FOR ALL CITIES
# ==========================================

def get_all_cities_weather(
    city_reference
):

    weather_data = {}

    for city, coords in city_reference.items():

        lat, lon = coords

        weather_data[city] = (
            get_city_weather(
                lat,
                lon
            )
        )

    return weather_data